version: '3.8'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - web
    volumes:
      - ./src/static:/var/www/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"

  db:
    image: postgres:13
    volumes:
      - /postgresql/bugu_shop_data:/var/lib/postgresql/data
    env_file:
      - ./.env

  web:
    build: ./src/
    depends_on:
      - db
    env_file:
      - ./.env
